function txt = rc40_class_guide(hwArray)
%RC40_CLASS_GUIDE  Full usage guide text for a HW class subsystem.
%
%   txt = RC40_CLASS_GUIDE(hwArray) returns a multi-line annotation that
%   documents, for the given HW class, everything needed to use the pins and
%   to integrate the generated code with the BSW:
%     - direction, data type, unit/range
%     - the HW struct access path (with the DevInp_/DevOutp_ index)
%     - the exact struct fields (from the Hw*.h headers)
%     - a short usage snippet
%
%   Placed as an annotation inside each HwInp/<class> or HwOutp/<class>
%   subsystem. <pin> is a placeholder for the physical pin (e.g. K81).
%
%   Grounded in the RC40 Hw*.h headers and datasheet.

    switch hwArray
        % ---------------- INPUTS (read from .outp_s) ----------------
        case 'AnU'
            txt = [ ...
                'AnU  (Analog Voltage Input)', newline, ...
                'DataType: u16   Range: 0~40000 mV', newline, ...
                'Read: HwInp_s.AnU_as[DevInp_<pin>_D].outp_s', newline, ...
                '  .u_mV_u16      analog voltage (mV)', newline, ...
                '  .stErrDetn_u8  error detection'];
        case 'AnI'
            txt = [ ...
                'AnI  (Analog Current Input)', newline, ...
                'DataType: u16   Range: 0~25000 uA', newline, ...
                'Read: HwInp_s.AnI_as[DevInp_<pin>_D].outp_s', newline, ...
                '  .i_uA_u16      analog current (uA)', newline, ...
                '  .stErrDetn_u8  error detection'];
        case 'Unused'
            txt = [ ...
                'Unused  (Use = OFF in RC40_Pinmap.xlsx)', newline, ...
                'Pins marked OFF are placed here and are NOT', newline, ...
                'included in the BSW integration snippets.', newline, ...
                'Set Use = ON to generate them in HwInp/HwOutp.'];
        case 'Dig'
            txt = [ ...
                'Dig  (Digital Input)', newline, ...
                'DataType: boolean (0/1)', newline, ...
                'Read: HwInp_s.Dig_as[DevInp_<pin>_D].outp_s', newline, ...
                '  .flg_l         digital state', newline, ...
                '  .stErrDetn_u8  error detection'];
        case 'FrqStd'
            txt = [ ...
                'FrqStd  (Frequency Input)', newline, ...
                'DataType: u32   Range: 0~20000 (unit 0.1 Hz)', newline, ...
                'Read: HwInp_s.FrqStd_as[DevInp_<pin>_D].outp_s', newline, ...
                '  .frq_p1Hz_u32        frequency (0.1 Hz)', newline, ...
                '  .ratDutyCyc_perml_u16 duty (0.1%)', newline, ...
                '  .tiPls_us_u32/.tiPerd_us_u32  pulse/period (us)', newline, ...
                '  .stErrDetn_u8        error detection'];
        case 'R'
            txt = [ ...
                'R  (Resistance Input)', newline, ...
                'DataType: u32   Range: 0~700000 Ohm', newline, ...
                'Read: HwInp_s.R_as[DevInp_<pin>_D].outp_s', newline, ...
                '  .r_Ohm_u32     resistance (Ohm)', newline, ...
                '  .stErrDetn_u8  error detection'];
        case 'Sent'
            txt = [ ...
                'Sent  (SENT Input, SAE J2716)', newline, ...
                'DataType: u16', newline, ...
                'Read: HwInp_s.Sent_as[DevInp_<pin>_D].outp_s', newline, ...
                '  .dataSerlMsg_u16      slow-channel data', newline, ...
                '  .flgNewSerlMsgRxd_l   new message flag', newline, ...
                '  .idSerlMsg_u8         message id', newline, ...
                '  .stErrDetn_u8         error detection'];

        % ---------------- OUTPUTS (write to .inp_s) ----------------
        case 'PropPwr'
            txt = [ ...
                'PropPwr  (Proportional Power Output)', newline, ...
                'DataType: u16   Range: 0~4000 mA (or duty 0~1000)', newline, ...
                'Write: HwOutp_s.PropPwr_as[DevOutp_<pin>[HS|LS]_D].inp_s', newline, ...
                '  .flgSp_l             = TRUE;', newline, ...
                '  .iSp_mA_u16          = <current mA>;', newline, ...
                '  .dutyCycSp_perml_u16 = <duty 0.1%>;', newline, ...
                '  .stErrReactn_e       = <ErrReactn>;'];
        case 'PropSig'
            txt = [ ...
                'PropSig  (Proportional Signal Output)', newline, ...
                'DataType: u16   Range: 0~1000 (duty 0.1%)', newline, ...
                'Write: HwOutp_s.PropSig_as[DevOutp_<pin>_D].inp_s', newline, ...
                '  .flgSp_l             = TRUE;', newline, ...
                '  .dutyCycSp_perml_u16 = <duty 0.1%>;', newline, ...
                '  .stErrReactn_e       = <ErrReactn>;'];
        case 'DigSig'
            txt = [ ...
                'DigSig  (Digital Signal Output)', newline, ...
                'DataType: boolean (0/1)', newline, ...
                'Write: HwOutp_s.DigSig_as[DevOutp_<pin>_D].inp_s', newline, ...
                '  .flgSp_l        = TRUE/FALSE;', newline, ...
                '  .stErrReactn_e  = <ErrReactn>;'];
        case 'AbsltU'
            txt = [ ...
                'AbsltU  (Analog Voltage Output)', newline, ...
                'DataType: u16   Range: 0~10000 mV', newline, ...
                'Write: HwOutp_s.AbsltU_as[DevOutp_<pin>_D].inp_s', newline, ...
                '  .uAbslt_mV_u16 = <voltage mV>;', newline, ...
                '  .stErrReactn_e = <ErrReactn>;'];
        otherwise
            txt = '';
    end
end
